blank_issues_enabled: true
contact_links:
  - name: Asana
    url: https://app.asana.com/1/1208680707766175/project/1210174060919452/list/1210173918087282
    about: For administrative tasks, please use Asana.